name: Cleanup Old Workflow Runs

on:
  # 这个工作流将在每天凌晨3点执行
  schedule:
    - cron: '0 3 * * *'
  # 你也可以手动触发这个工作流
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js for script
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install @octokit/rest

      - name: Delete all workflow runs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          #!/bin/bash
          set -e

          node <<EOF
            const { Octokit } = require("@octokit/rest");
            const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

            async function deleteAllRuns() {
              try {
                let page = 1;
                while (true) {
                  const response = await octokit.actions.listWorkflowRunsForRepo({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    per_page: 100,
                    page: page++
                  });

                  if (response.data.workflow_runs.length === 0) break;

                  for (const run of response.data.workflow_runs) {
                    console.log(`Deleting run ID ${run.id}`);
                    await octokit.actions.deleteWorkflowRun({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      run_id: run.id
                    });
                  }
                }
              } catch (error) {
                console.error("Error deleting workflow runs:", error);
              }
            }

            deleteAllRuns();
          EOF
