name: Cleanup All Old Workflow Runs
on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜执行
  workflow_dispatch:  # 手动触发器
jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete all old workflow runs
        uses: c-hive/gha-remove-workflow-runs@v1
        with:
          retain_days: 0  # 设置为 0，表示删除所有旧的 runs
          repo_token: ${{ secrets.GITHUB_TOKEN }}