name: Update xiaoyu and fan jar

on:
  push:   # 推送触发
  # schedule:
    #- cron: '0 0 * * *'
  workflow_dispatch:  # 添加手动触发器

jobs:
  update-spider:
    runs-on: ubuntu-latest

    steps:
      # 第 1 步：检查仓库
      - name: Checkout repository
        uses: actions/checkout@v2

      # 第 2 步：设置 Python
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # 第 3 步：安装必要的依赖项
      - name: Install Dependencies
        run: python -m pip install requests

      # 第 4 步：更新 xiaoyu spider 字段
      - name: Update Xiaoyu Spider Field
        run: |
          # 从新 URL 获取现有数据
          response=$(curl -s "https://cdn09022024.gitlink.org.cn/api/v1/repos/yf1688/box/raw/master/jar/xiaoyu.txt")
          
          # 确保 jar 目录存在
          mkdir -p ${{ github.workspace }}/jar
          
          # 将获取的数据保存到文件中
          file="${{ github.workspace }}/jar/xiaoyu.txt"
          echo "$response" > "$file"
          
          # 文件夹ID
          id=396663
          
          # 使用 GitHub Secrets 中的 KSTORE_TOKEN
          curl -X POST "https://upload.kstore.space/upload/$id?access_token=${{ secrets.KSTORE_TOKEN }}" -F "file=@$file"

      # 第 5 步：更新 fan spider 字段
      - name: Update Fan Spider Field
        run: |
          # 从新 URL 获取现有数据
          response=$(curl -s "https://cdn09022024.gitlink.org.cn/api/v1/repos/yf1688/box/raw/master/jar/fan.txt")
          
          # 确保 jar 目录存在
          mkdir -p ${{ github.workspace }}/jar
          
          # 将获取的数据保存到文件中
          file="${{ github.workspace }}/jar/fan.txt"
          echo "$response" > "$file"
          
          # 文件夹ID
          id=396663
          
          # 使用 GitHub Secrets 中的 KSTORE_TOKEN
          curl -X POST "https://upload.kstore.space/upload/$id?access_token=${{ secrets.KSTORE_TOKEN }}" -F "file=@$file"
